#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const distDir = path.join(rootDir, 'dist');
const clientsDir = path.join(rootDir, 'src', 'data', 'clients');

async function prerender() {
  const indexHtmlPath = path.join(distDir, 'index.html');
  if (!fs.existsSync(indexHtmlPath)) {
    console.error('\x1b[31mError: dist/index.html tidak ditemukan. Jalankan vite build terlebih dahulu.\x1b[0m');
    process.exit(1);
  }

  const rawTemplate = fs.readFileSync(indexHtmlPath, 'utf8');

  // Helper untuk membersihkan tag meta lama agar tidak terjadi duplikasi
  function cleanHead(html) {
    return html
      .replace(/<title>[\s\S]*?<\/title>/gi, '')
      .replace(/<meta\s+name=["']description["'][^>]*>/gi, '')
      .replace(/<meta\s+property=["']og:[^"']+["'][^>]*>/gi, '')
      .replace(/<meta\s+name=["']twitter:[^"']+["'][^>]*>/gi, '')
      .replace(/<meta\s+name=["']robots["'][^>]*>/gi, '');
  }

  // 1. Modifikasi dist/index.html (Halaman root produksi netral) agar diberi noindex
  let rootHtml = cleanHead(rawTemplate);
  const brandName = process.env.VITE_BRAND_NAME || 'Kalyana Undangan Adat';
  const rootMetaTags = `
    <title>${escapeHtml(brandName)}</title>
    <meta name="robots" content="noindex, nofollow" />
  `;
  rootHtml = rootHtml.replace('</head>', `${rootMetaTags}\n  </head>`);
  fs.writeFileSync(indexHtmlPath, rootHtml, 'utf8');
  console.log('\x1b[32m✔ dist/index.html disuntikkan meta noindex untuk produksi.\x1b[0m');

  // 2. Scan semua konfigurasi klien di src/data/clients/*.js
  const clientFiles = fs.readdirSync(clientsDir).filter(
    (f) => f.endsWith('.js') && !f.includes('client-template')
  );

  console.log(`\x1b[36mMemulai pre-render Open Graph untuk ${clientFiles.length} klien...\x1b[0m`);

  for (const file of clientFiles) {
    const filePath = path.join(clientsDir, file);
    try {
      const mod = await import(pathToFileURL(filePath).href);
      const config = mod.default || Object.values(mod).find((v) => v && typeof v === 'object' && v.slug);

      if (!config || !config.slug) {
        continue;
      }

      const slug = String(config.slug).toLowerCase().trim();
      const meta = config.meta || {};
      const title = meta.title || `The Wedding of ${slug}`;
      const description = meta.description || 'Undangan Pernikahan Adat Tradisional Digital';
      const rawOgImage = meta.ogImage || `/clients/${slug}/couple.jpg`;
      const favicon = meta.favicon || '/favicon.svg';

      // Base URL resolution for absolute OG tags (required by WhatsApp/Facebook/Twitter crawlers)
      const rawBaseUrl = process.env.VITE_APP_URL ||
        (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` :
        (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : ''));
      const baseUrl = rawBaseUrl.replace(/\/+$/, '');

      const ogImage = rawOgImage.startsWith('http://') || rawOgImage.startsWith('https://')
        ? rawOgImage
        : (baseUrl ? `${baseUrl}${rawOgImage.startsWith('/') ? '' : '/'}${rawOgImage}` : rawOgImage);

      const ogUrl = baseUrl ? `${baseUrl}/${slug}` : `/${slug}`;

      // Buat tag meta Open Graph & Twitter Cards lengkap
      const ogMetaTags = `
    <!-- Pre-rendered Open Graph & SEO (Auto-generated by build) -->
    <title>${escapeHtml(title)}</title>
    <meta name="description" content="${escapeHtml(description)}" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="${escapeHtml(title)}" />
    <meta property="og:locale" content="id_ID" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:image" content="${escapeHtml(ogImage)}" />
    <meta property="og:image:alt" content="${escapeHtml(title)}" />
    <meta property="og:url" content="${escapeHtml(ogUrl)}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${escapeHtml(ogImage)}" />
  `;

      let clientHtml = cleanHead(rawTemplate);

      // Ganti favicon bila berbeda
      if (favicon && clientHtml.includes('rel="icon"')) {
        clientHtml = clientHtml.replace(/<link rel="icon"[^>]*>/i, `<link rel="icon" href="${escapeHtml(favicon)}" />`);
      }

      // Sisipkan tag OG sebelum </head>
      clientHtml = clientHtml.replace('</head>', `${ogMetaTags}\n  </head>`);

      // Tulis output pre-render ke dist/{slug}/index.html dan dist/{slug}.html
      const clientOutputDir = path.join(distDir, slug);
      if (!fs.existsSync(clientOutputDir)) {
        fs.mkdirSync(clientOutputDir, { recursive: true });
      }
      fs.writeFileSync(path.join(clientOutputDir, 'index.html'), clientHtml, 'utf8');
      fs.writeFileSync(path.join(distDir, `${slug}.html`), clientHtml, 'utf8');

      // 3. Pre-render halaman generator dengan tag noindex
      const generatorOutputDir = path.join(clientOutputDir, 'generator');
      if (!fs.existsSync(generatorOutputDir)) {
        fs.mkdirSync(generatorOutputDir, { recursive: true });
      }

      let generatorHtml = cleanHead(rawTemplate);
      const generatorTags = `
    <!-- Generator Tamu - Protected Admin Route -->
    <title>Generator Link Tamu - /${slug}</title>
    <meta name="robots" content="noindex, nofollow" />
  `;
      generatorHtml = generatorHtml.replace('</head>', `${generatorTags}\n  </head>`);

      fs.writeFileSync(path.join(generatorOutputDir, 'index.html'), generatorHtml, 'utf8');
      fs.writeFileSync(path.join(clientOutputDir, 'generator.html'), generatorHtml, 'utf8');

      console.log(`\x1b[32m✔ [${slug}]\x1b[0m Pre-rendered OG: "${title}" -> dist/${slug}/index.html`);
    } catch (err) {
      console.warn(`\x1b[33m⚠ Gagal melakukan pre-render untuk ${file}:\x1b[0m`, err);
    }
  }

  console.log('\x1b[32m✨ Pre-render Open Graph & noindex selesai dengan sukses! ✨\x1b[0m\n');
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

prerender();
